**Tensor Basics**

● Create and inspect the following tensors:

○ From a list using torch.tensor()

○ Zeros using torch.zeros()

○ Ones using torch.ones()

○ Random values using torch.rand()

In [2]:
import torch

Google Colab have pre-installed PyTorch, so there is no need to install it manually.However, if  using Jupyter Notebook we  first install pytorch by running the following command in a code cell
!pip install torch torchvision torchaudio


In [11]:
print(torch.__version__)

2.6.0+cu124


In [10]:
if torch.cuda.is_available():
  print("cuda available")
else:
  print("cuda not available")

cuda not available


first i checked if PyTorch is working correctly suing torch.___version___. I also checked if my system has a GPU, which helps in running programs faster.

In [31]:
torch.tensor(([1,2,3],[1,4,5]))

tensor([[1, 2, 3],
        [1, 4, 5]])

In [18]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [19]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [22]:
a=torch.rand(2,3)
a

tensor([[0.5926, 0.8575, 0.8517],
        [0.3612, 0.6554, 0.8838]])

In this task, I got familiar with how to create tensors in PyTorch and explored different ways to fill them with data.

I learned that a tensor is basically a list or a matrix it can store numbers in many dimensions

I practiced using the following functions:

torch.tensor() This lets me create a tensor from a regular Python list.

torch.zeros() This creates a tensor filled with only 0s.

torch.ones() This makes a tensor filled with 1s.

torch.rand() This creates a tensor filled with random numbers between 0 and 1.


For each tensor, print its:

○ Shape

○ Data type

○ Device (CPU/GPU)

In [25]:
a.shape

torch.Size([2, 3])

In [24]:
a.dtype

torch.float32

In [13]:
cpu = torch.tensor([1, 2, 3])

if torch.cuda.is_available():
    gpu = cpu.to('cuda')
    print("\nTensor moved to GPU:")
    print("  Device:", gpu.device)
else:
    print("\nCUDA not available.")
    print("  Device:", cpu.device)



Tensor moved to GPU:
  Device: cuda:0


Once I created these tensors, I printed out their shape (like how many rows and columns they have), Their data type (e.g., float32, int64), and The device (whether they’re stored on the CPU or GPU).

** Basic Operations Practice**\
● Create two (3x3) tensors and perform:\
○ Element-wise addition, subtraction, multiplication\
○ Matrix multiplication using @ and torch.matmul()\
○ Reshape using .reshape()\
○ Transpose, stack, squeeze, unsqueeze

In [40]:
a=torch.tensor(([1,2,3],[4,5,6],[7,8,9]))
b=torch.tensor(([1,2,3],[4,5,6],[7,8,9]))

In [35]:
a+b

tensor([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [36]:
a-b

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [38]:
a*b

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

I created two tensors of size 3x3 and performed

Addition: I added both tensors together, element by element.

Subtraction: Subtracted one tensor from the other, also element by element.

Multiplication Multiplied the numbers at the same positions in both tensors.

In [41]:
a@b

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [43]:
torch.matmul(a, b)

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

Next, I tried matrix multiplication,It follows the rules of linear algebra.

@ symbol

torch.matmul()

Both give the same results.

In [48]:
a.reshape(9)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

    
I reshaped one of the tensors using .reshape() from a 3×3 shape to a 1-9 shape.

In [50]:
a.T

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

I also transposed a tensor using .T, which flips rows and columns. So, a 3x3 tensor still stays 3x3, but the values will be changed.

In [51]:

torch.stack((a, b), dim=0)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

I used torch.stack() to combine tensors.

In [67]:
a.squeeze()

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [53]:
a.unsqueeze(0)  # Shape becomes (1, 3, 3)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

squeeze() removes extra dimensions (like shape [1, 3, 3] becomes [3, 3]).

unsqueeze() adds a dimension (like [3, 3] becomes [1, 3, 3]).

**Custom Computation Task**

● Write a function to normalize a tensor between 0 and 1 (min-max scaling)\
● Write another function that simulates y = 2x + 1 for 1D tensor x with 100 values


In [19]:
import torch
def normalize_tensor(tensor):
    min_val = tensor.min()
    max_val = tensor.max()
    normalized = (tensor - min_val) / (max_val - min_val)
    return normalized
x = torch.tensor([1, 2,3, 4])
normalized_x = normalize_tensor(x)
print("Original Tensor:", x)
print("Normalized Tensor:", normalized_x)


Original Tensor: tensor([1, 2, 3, 4])
Normalized Tensor: tensor([0.0000, 0.3333, 0.6667, 1.0000])


 I found the minimum and maximum values of the tensor using .min() and .max() functions. Then I applied the min-max normalization formula: (tensor - min) / (max - min), which scales all the values in the tensor between 0 and 1. After defining the function, I created a simple tensor x = [1, 2, 3, 4] and passed it to the function. Finally, I printed both the original and normalized tensors.

In [74]:
x = torch.rand(100)
# Compute y = 2x + 1
y = 2 * x + 1
print("x values:", x)
print("y values (2x + 1):", y)

x values: tensor([0.4238, 0.7133, 0.8621, 0.0038, 0.9264, 0.9540, 0.4094, 0.9390, 0.8837,
        0.0572, 0.9738, 0.7088, 0.8874, 0.2186, 0.8779, 0.4348, 0.2695, 0.3055,
        0.1462, 0.0088, 0.9463, 0.7608, 0.4820, 0.9190, 0.7873, 0.3484, 0.7550,
        0.2919, 0.2831, 0.1658, 0.5224, 0.5730, 0.6831, 0.9726, 0.0068, 0.0526,
        0.9825, 0.2926, 0.9405, 0.3775, 0.0112, 0.5564, 0.5566, 0.0034, 0.5797,
        0.2431, 0.5957, 0.0260, 0.3856, 0.6439, 0.9254, 0.6062, 0.9403, 0.0859,
        0.5196, 0.3488, 0.0464, 0.2223, 0.0394, 0.6604, 0.5513, 0.5888, 0.5141,
        0.0256, 0.8425, 0.4803, 0.0105, 0.4724, 0.2350, 0.1509, 0.1950, 0.3174,
        0.7263, 0.6284, 0.4602, 0.3919, 0.2825, 0.2818, 0.0560, 0.2703, 0.8498,
        0.3190, 0.2515, 0.1588, 0.3127, 0.3913, 0.7459, 0.2997, 0.4853, 0.2321,
        0.6861, 0.0914, 0.8330, 0.5950, 0.2532, 0.3613, 0.5458, 0.6766, 0.9839,
        0.9566])
y values (2x + 1): tensor([1.8477, 2.4265, 2.7242, 1.0077, 2.8527, 2.9081, 1.8189, 2.8781, 2.

I created another random tensor x with 100 values using torch.rand(100).
Then, I applied the equation by doing y = 2 * x + 1.

This gave me a new tensor y, where each value is based on the equation.
.